# Generated by Django 4.2.1 on 2024-06-16 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('url', models.URLField()),
                ('ip', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('mobile', models.BooleanField()),
                ('entered_at', models.DateTimeField()),
            ],
        ),
    ]
