# Generated by Django 4.2.1 on 2024-06-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
