# Generated by Django 4.2.16 on 2024-11-30 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('url', models.URLField(null=True)),
                ('ip', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('mobile', models.BooleanField()),
                ('entered_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
