# Generated by Django 4.2.14 on 2024-10-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='left_at',
            field=models.DateTimeField(null=True),
        ),
    ]
