# Generated by Django 4.2.14 on 2024-10-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_email_customer_website_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website_type',
            field=models.TextField(blank=True),
        ),
    ]
